#!/bin/bash

# This is just a way of running ansible-tests without having to see the massive
# setup log that precedes the actual test output.

command=$1
shift

case $command in
    units)
        ansible-test units --docker --color yes "$@" 2> /dev/null | \
            sed -ne '/Unit test with/,$p'
        ;;
    sanity)
        ansible-test sanity --docker --color yes "$@" 2> /dev/null | \
            sed -ne '/Running sanity test/,$p' | \
            grep -v '^Requirement already satisfied:'
        ;;
    *)
        ansible-test $command --docker --color yes "$@" 2> /dev/null
        ;;
esac
