#!/bin/bash

# This is just a way of running ansible-tests without having to see the massive
# setup log that precedes the actual test output.

command=$1
shift

ANSIBLE_TEST=/home/vagrant/ansible/bin/ansible-test

case $command in
    units)
        $ANSIBLE_TEST units --docker --color=yes "$@" | \
            sed -ne '/Unit test with/,$p'
        ;;
    sanity)
        $ANSIBLE_TEST sanity --docker --color=yes "$@" | \
            sed -ne '/Running sanity test/,$p' | \
            grep -v '^Requirement already satisfied:'
        ;;
    *)
        $ANSIBLE_TEST $command --docker --color=yes "$@"
        ;;
esac
