#!/bin/bash

# This is just a way of running ansible-tests without having to see the massive
# amount of debug logging it produces. Printouts to stderr will still show.

command=$1
shift

ANSIBLE_TEST=/home/vagrant/ansible/bin/ansible-test

case $command in
    units)
        $ANSIBLE_TEST units "$@" --color=yes | \
            sed -ne '/Unit test with/,$p'
        ;;
    sanity)
        $ANSIBLE_TEST sanity "$@" --color=yes | \
            sed -ne '/Running sanity test/,$p' | \
            grep -v '^Requirement already satisfied:'
        ;;
    *)
        $ANSIBLE_TEST $command "$@" --color=yes
        ;;
esac
