---
- name: Install required os packages
  apt:
    update_cache: yes
    name:
      - build-essential
      - docker.io
      - emacs
      - libffi-dev
      - libssl-dev
      - python-dev
      - python3-venv
    state: present

- name: Enroll vagrant in the docker group
  user:
    name: vagrant
    groups: docker
    append: yes
